export const c = {
    isFolder: "isFolder",
    isFile: "isFile",
    hasInnerSelection: "hasInnerSelection",
    selected: "selected",
    sorted: "sorted",
    asc: "asc",
    desc: "desc",
    name: "name",
    dropdownToggle: "dropdown-toggle",
    type: "type",
    size: "size",
    modified: "modified",
    ext: "ext",
    opened: "opened",
    playing: "playing",
    paused: "paused",
    stopped: "stopped",
    fileRow: "fileRow",
    small: "small",
    progress: "progress",
    firstItemInPage: "firstItemInPage",
    lastItemInPage: "lastItemInPage",

    selectionDark: "#6241a6",
    selection: "#a276f8",
    selectionLight: "#a97eff",
} as const
